### ISSUE TITLE
Crash on RLMAccessor.mm line 73

### ISSUE THREAD

**Issue by omerbaskurt** [mentrena/SyncKit#107]
Hi @mentrena, I got a crash report on crashlytics that affected the same user several times. This happened after I've changed the realm model. I didn't get any crashes on my test runs. I'm attaching the stack trace. Thanks.
<img width="1012" alt="Screen Shot 2019-11-25 at 8 22 59 AM" src="https://user-images.githubusercontent.com/13778103/69544099-06e0ea80-0f5d-11ea-96ff-51e84e89d898.png">
<img width="1043" alt="Screen Shot 2019-11-25 at 8 23 24 AM" src="https://user-images.githubusercontent.com/13778103/69544126-12341600-0f5d-11ea-90ae-4fa471579ec7.png">

**Comment by mentrena** [comment]
Hi @omerbaskurt could you share your realm models (old and new)?

**Comment by omerbaskurt** [comment]
I added two fields to the old model:

Old model: 
```
{
    @objc dynamic public private(set) var id = ""
    @objc dynamic public private(set) var date = ""
    @objc dynamic public private(set) var dateNS = Date()
    @objc dynamic public private(set) var startTime = ""
    @objc dynamic public private(set) var endTime = ""
    @objc dynamic public private(set) var iconIndex = 0
    @objc dynamic public private(set) var notes = ""
    @objc dynamic public private(set) var intStartTime = 0
}
```

New model: 
```
{
    @objc dynamic public private(set) var id = ""
    @objc dynamic public private(set) var date = ""
    @objc dynamic public private(set) var dateNS = Date()
    @objc dynamic public private(set) var startTime = ""
    @objc dynamic public private(set) var endTime = ""
    @objc dynamic public private(set) var iconIndex = 0
    @objc dynamic public private(set) var notes = ""
    @objc dynamic public private(set) var intStartTime = 0
    @objc dynamic public private(set) var colorHex = ""
    @objc dynamic public private(set) var shortText = ""
}
```

**Comment by omerbaskurt** [comment]
Any updates on this?

**Comment by mentrena** [comment]
Did the crash happen on a version of the app running the newer model or on one running the older model?
And just in case, have you set the `compatibilityVersion` property on `CloudKitSynchronizer`?

**Comment by omerbaskurt** [comment]
On a newer model. I didn't set it, does that indicate the local realm version?

**Comment by mentrena** [comment]
You can set it and increase it when you make a new release, to avoid older versions of your app downloading records created by the new version –sync ends with a `higherModelVersionFound` that you can detect to prompt users to upgrade.

In any case this sounds like a bug. I need to think about it, but my first thought is that:

- A record created by a previous version of your app didn't have a `colorHex` or `shortText` property.
- That record gets downloaded by a newer version of the app, and because those properties are not set in the record, SyncKit will try to set the property on the object to nil, but your type is not optional so Realm complains and you get a crash.

This logic is needed to be able to set properties to nil, so this scenario is problematic. `NSNull` doesn't conform to `CKRecordValue` so I can't use it here.

In the meantime a quick fix for you would be to declare your new properties as `String?`, if that's an option.

**Comment by mentrena** [comment]
`0.7.9` has a fix for non-optional properties in RealmSwift, so it's not needed to make them optional any more. Thanks for reporting.
