### ISSUE TITLE
Stuck in a loop of partial errors

### ISSUE THREAD

**Issue by Rodge73** [mentrena/SyncKit#111]
Hi. 
On one of the devices that uses SyncKit 0.7.10 (Coredata), it's stuck in an endless loop. Running on iOS13. 
The error is a Partial Faillure, seemingly due to 'record to insert already exists' and 'client oplock error updating record'. See error belowlog for details. I added some debugstatements in the uploadRecords() function in CloudKitSynchronizer+Synch.swift. The error is an operationError, but not isLimitExceeded. Synckit just keeps retrying. 
I'm not sure how this issue was created in the past but I'm guessing due to slow wifi connections on the iOS device.

Any idea to get out of this loop? Or any other way to fix or circumvent?
Is there a way to somehow delete related (or even all) records on CloudKit and sync again?

Thanks for your help, Rodge

"CloudKitSynchronizer >> Initiating synchronization"
"QSCloudKitSynchronizer >> uploading 91 records with batchsize 200 (uploadRecords())"
"QSCloudKitSynchronizer >> operationerror: <CKError 0x283da7d80: \"Partial Failure\" (2/1011); \"Failed to modify some records\"; uuid = 82E30FD8-4496-49F2-A497-9B086D5A6BBA; container ID = \"iCloud.be.myapp \"; partial errors: {\n\tPerson.F368A074-0466-4360-87C9-5F0023851EDD-2786-000004D93DC7445B:(MyappZone:__defaultOwner__) = <CKError 0x283da4e70: \"Server Record Changed\" (14/2004); server message = \"record to insert already exists\"; uuid = 82E30FD8-4496-49F2-A497-9B086D5A6BBA>\n\tPayment.2ACCE118-9459-4DB9-91BE-31D5B937DC72-2786-000004D50C7F0E2B:(MyappZone:__defaultOwner__) = <CKError 0x283da4db0: \"Server Record Changed\" (14/2004); server message = \"record to insert already exists\"; uuid = 82E30FD8-4496-49F2-A497-9B086D5A6BBA>\n\tPerson.0986031B-BC87-4F5A-BA8C-F978F9D089B4-1505-000003E3521BDEAD:(MyappZone:__defaultOwner__) = <CKError 0x283da3b70: \"Server Record Changed\" (14/2004); server message = \"client oplock error updating record\"; uuid = 82E30FD8-4496-49F2-A497-9B086D5A6BBA>\n\t... 88 \"Batch Request Failed\" CKError\'s omited ...\n}> "
"QSCloudKitSynchronizer >> uploading 91 records with batchsize 200 (uploadRecords())"
"QSCloudKitSynchronizer >> operationerror: <CKError 0x283da80f0: \"Partial Failure\" (2/1011); \"Failed to modify some records\"; uuid = 843EC848-A2BB-4631-926E-670B80B2C821; container ID = \"iCloud.be.myapp\"; partial errors: {\n\tPerson.F368A074-0466-4360-87C9-5F0023851EDD-2786-000004D93DC7445B:(MyappZone:__defaultOwner__) = <CKError 0x283dbf2d0: \"Server Record Changed\" (14/2004); server message = \"record to insert already exists\"; uuid = 843EC848-A2BB-4631-926E-670B80B2C821>\n\tPayment.2ACCE118-9459-4DB9-91BE-31D5B937DC72-2786-000004D50C7F0E2B:(MyappZone:__defaultOwner__) = <CKError 0x283dfcc90: \"Server Record Changed\" (14/2004); server message = \"record to insert already exists\"; uuid = 843EC848-A2BB-4631-926E-670B80B2C821>\n\tPerson.0986031B-BC87-4F5A-BA8C-F978F9D089B4-1505-000003E3521BDEAD:(MyappZone:__defaultOwner__) = <CKError 0x283dbdc80: \"Server Record Changed\" (14/2004); server message = \"client oplock error updating record\"; uuid = 843EC848-A2BB-4631-926E-670B80B2C821>\n\t... 88 \"Batch Request Failed\" CKError\'s omited ...\n}> "
.....
This keeps repeating.

**Comment by mentrena** [comment]
Hi Rodge,

Can you still reproduce this error?
It seems that, because the error is a "Server Record Changed" error, the library thinks it could fix it by downloading any new records from the cloud (see CloudKitSynchronizer+Sync.swift:308)
At that point, the up-to-date record would normally be downloaded from iCloud, updated locally, and the changes would be able to get uploaded at that point.
If the library is stuck then I'm assuming it's not downloading the new record somehow. Can you see what's happening inside `fetchChanges()` ? 
Are no records being downloaded? This would suggest the iCloud token was saved at some point, but the records that were downloaded were not persisted correctly.
I would need to investigate this but let me know if you can reproduce so we can get some more info.

To answer your other question, take a look at the `deleteRecordZone` function to delete a record zone on iCloud –along with any records in it.

Another option would be to make use of `eraseLocalMetadata()` to delete only the local syncing metadata, so any data on iCloud will stay there. Then you could create a new synchroniser for your model and sync again. If you do this, you might want to delete your local data as well to avoid duplicates depending on how you manage your object identifier.

**Comment by Rodge73** [comment]
Hi Manuel, Thanks for getting back. Unfortunately, I keep having this issue.
I have no way to reproduce yet, but after restoring one iPad from scratch this happened again.
First, the syncs are starting to fail, I don't know why as SyncKit is working fine for >3 years. 

This error stays within the SyncKit stack without ever reporting an error to the app. It just keeps trying to sync forever (as long as the app is in the foreground). Trying to restart the sync would immediately result in alreadySyncing error. So the app has no way to really detect this problem even exists.

After a certain amount of time (days) of this, SyncKit does start to crash. The crash is in CoreDataAdapter+Private.sift in function recordToUpload:

```
context.performAndWait {
      originalObject = self.managedObject(entityName: entityType, identifier: objectID, context: context) --> this one becomes nil
       entityDescription = NSEntityDescription.entity(forEntityName: entityType, in: context)
       let primaryKey = self.identifierFieldName(forEntity: entityType)
       // Add attributes
       entityDescription.attributesByName.forEach({ (attributeName, attributeDescription) in
           if attributeName != primaryKey &&
               (entityState == .new || changedKeys.contains(attributeName)) {
               let value = originalObject.value(forKey: attributeName) -->leading to Fatal Error here: unexpectedly found nil while implicitly unwrapping an optional value
```

So first I'll try to get the deleteRecordZone to work. I prefer deleting server data as the local CD data is typically more recent. Or do you see another way to avoid this crash?
Once I do that, I hope to be able to reproduce the initial issue, and answer your questions above.

**Comment by Rodge73** [comment]
In the meantime I've tried the `deleteRecordZone()` which worked fine. Of course it means deleting all iCloud data and re-sync. Also I've update to SyncKit 0.7.11.
Now I have to wait until the initial problem occurs again. This is hard to predict as I don't know how to reproduce.

Also` eraseLocalMetadata()` is implemented an on a 'clean' database it doesn't seem to have negative effect. I didn't try yet when issues occur. All CD items have a uniqueIdentifier. Is this what you meant? I'm not sure what this function does and what risks could be... When I delete local data, these deletions would typically sync, so cause deletion on iCloud. Is there a way to delete only local and force resync with iCloud?
thanks, Rodge

**Comment by mentrena** [comment]
>  Is there a way to delete only local and force resync with iCloud?

Yes, as I mentioned the example project shows one way to do it. Check out the [AppDelegate](https://github.com/mentrena/SyncKit/blob/master/Example/CoreData/SyncKitCoreDataExample/SyncKitCoreDataExample/AppDelegate.swift)
`eraseLocalMetadata()` deletes the extra data that SyncKit uses to keep track of changes and synchronisation, it doesn't touch your own data (SyncKit uses its own CoreData stack).

In the example project, when you enable SyncKit, you get the option to keep your local data or to delete it (so after syncing you get only what's on iCloud). To do that, the app just deletes the CoreData files. This is logic that belongs in the example project, not the SyncKit library, so you would have to implement that logic in your own app, but the example project shows how to do it.

Let me know if you manage to reproduce again with the latest version. Is your project open source or would it be possible for me to debug it somehow?

**Comment by mentrena** [comment]
I think there was an edge case with a partial failure upload where some records might have become outdated. That case has been fixed on 0.7.14, but feel free to reopen if the issue ever happens again.

**Comment by w8wjb** [comment]
I am having this problem as well. I think I know what the problem, but I'm not sure yet what the fix is.

First off, I have looked into my `QSSyncStore` sqlite database and found that I have duplicated `QSSyncedEntity` records, where the identifier field matches. I am assuming that this is not supposed to happen, and that field is supposed to be unique, even though there is no constraint on the database that enforces it.

My theory about how this happened is that it may be a race condition of two different threads in the app. I have a process that pre-populates default records in the main database when the app starts for the very first time. I use very specific IDs for these records to prevent duplication of the records when synced with the cloud. So, if I have two devices that are not connected to iCloud, that are then subsequently synchronized, if I were to use random IDs, then I would end up with duplicate records, from a conventional standpoint. Or to be specific, these are chicken breeds. If device A records a "Leghorn" chicken and device B also records a "Leghorn" chicken, when they are ultimately synchronized, I want them to both point to the same breed record, not "Leghorn A" and "Leghorn B".

This problem happens once the second device comes online. So, when the first device comes online, there is no iCloud zone yet and so it simply pushes all of its local records up to the newly created CKZone. When the second device comes online, two things happen simultaneously: the synchronizer starts pulling the existing records down from the cloud and the process that populates defaults also kicks off. I suspect that one record in the QSSyncStore is coming from the changes being made in the main NSManagedObjectContext and the other one is coming in as CKRecords come down from the cloud. I also suspect that most people do not encounter this problem because they may be using random IDs.

Perhaps you can confirm or deny whether this is even a thing that might be possible?

One solution I attempted was to handle the CKError that is returned by the synchronize callback, inspect the `CKError.partialErrorsByItemID` and pull out the `CKError.Code.serverRecordChanged` entries. I thought maybe if I called `CoreDataAdapter.deleteRecords(with recordIDs: [CKRecord.ID])` it would delete both duplicate records in `QSSyncStore` and attempt to resynchronize those records again (sort of a less drastic solution than `eraseLocalMetadata()`). But it crashes because `targetImportContext` is nil

Hypothetically, I could maybe delay the default creation until after the sync is done, but that might be a bit tricky and would have to work if there was not an iCloud account connected.

**Comment by w8wjb** [comment]
I found my race condition, but it was different than I thought. I had an event that I thought was happening only once (checking the status of the user's iCloud account) and in response to that event it was initializing a new CloudKitSynchronizer. I discovered that, under certain conditions, the event could be triggered multiple times simultaneously and this could cause more than one CloudKitSynchronizers to be created, pointing at the same backing store. I discovered this because I happened to put a breakpoint in `CoreDataAdapter.performInitialSetup()` and realized that it was hitting the breakpoint more than once.

I solved the race condition by a) first checking to see if the variable holding CloudKitSynchronizer was nil before initializing a new one and b) doing this in a `NSManagedObjectContext.perform(...)` block in order to serialize access and avoid a race condition.

**Comment by mentrena** [comment]
I think your issue was different either way to the one originally mentioned in the ticket, but good that you found a solution :)
I would add that, for the use case of creating the same object on two devices (Leghorn in your example), I would maybe use a different identifier (a uuid) and then add extra logic to remove duplicates from Core Data. It probably means more work but sounds more failproof to me.
