### ISSUE TITLE
Option for storing CKAssets as files instead of NSData in Realm

### ISSUE THREAD

**Issue by torfluor** [mentrena/SyncKit#135]
While looking at the source code for SyncKit I noticed that CKAssets are stored as NSData in the Realm database. According to the Realm documentation there is a hard limit on 16MB for storing data:

> Data and String properties cannot hold data exceeding 16MB in size. To store larger amounts of data, either break it up into 16MB chunks or store it directly on the file system, storing paths to these files in the Realm. An exception will be thrown at runtime if your app attempts to store more than 16MB in a single property.

This poses a problem for apps that want to sync and store larger files like video and audio. 
Would it be possible to store the assets as files on the filesystem and just store the URL in the database?
I would be more than happy to help out with this, but I have limited experience with CloudKit and Realm so I would need some guidance :)

**Comment by mentrena** [comment]
I think it would be possible to add functions to the `RealmSwiftAdapterDelegate` to manually provide/save the CKRecord for a given object, so your code would get a chance to read the data from your file system and attach it to the record, then on the device downloading the record your code would be able to save that data to disk instead of Realm. I'll have a look at it.

**Comment by mentrena** [comment]
Hey @torfluor , the current tag 0.8.0 adds a new delegate you can provide to do custom record processing, see: https://github.com/mentrena/SyncKit/blob/fd24289dc213d3c2b95ab8fd746c0017e61e6b57/SyncKit/Classes/RealmSwift/RealmSwiftAdapter.swift#L35
In the upload method you can check for your property that contains a fileURL, create a CKAsset using that URL and assign it to the record so it gets sent to CloudKit.
When downloading, you would check for that property, store the data from the CKAsset on the local device and assign the fileURL to the Realm object.
You would only need to keep in mind that SyncKit wouldn't detect changes in the data, only changes to your object's properties.

If you're using Carthage I believe you should be able to install 0.8.0. If you're using Cocoapods I'm afraid Realm has been having some problems since Xcode 12 came out and Cocoapods is failing to validate the spec (see https://github.com/realm/realm-cocoa/issues/6800)

**Comment by mentrena** [comment]
Actually managed to publish 0.8.0 using the Xcode 11.3 toolchain, I'll close here.

**Comment by torfluor** [comment]
Thank you so much for this change! It works great :)
