### ISSUE TITLE
Error after changing the data type of a column

### ISSUE THREAD

**Issue by sskjames** [mentrena/SyncKit#156]
Hi,

We've just started to use SyncKit, and we are really thankful for this library.
After we started using, we had to change a column's data type from Int to String. 
After this change, I'm getting this error:

```
Optional(<CKError 0x281de8630: "Partial Failure" (2/1011); "Failed to modify some records"; uuid = 06B8F391-A448-464C-B72E-116BA351803B; container ID = "iCloud.com.xyz"; partial errors: {ServingInfo.1:(QSCloudKitCustomZoneName:defaultOwner) = <CKError 0x281deba80: "Invalid Arguments" (12/2006); server message = "invalid attempt to set value type STRING for field 'foodId' for type 'ServingInfo', defined to be: NUMBER_INT64"; uuid = 06B8F391-A448-464C-B72E-116BA351803B>... 5 "Batch Request Failed" CKError's omited ...}>)
```

Unfortunately, I couldn't change the data type of this column from CloudKit dashboard. 
Though the current version of our app is still under development, we've published the schema to CloudKit "production" environment, for testing purposes.
What is the proper way to change the data type of column in a CloudKit record? Kindly advise.
We are using Realm for the local database.

**Comment by mentrena** [comment]
Hi, I'm afraid that's a general CloudKit consideration so there's nothing I can do in the library.
If your app is still in development and you don't care about test data the easiest solution might be creating a new container. Otherwise I would try to add a new field to the entity with the right type, instead of changing the type of an existing field.

I would also advise setting a `compatibilityVersion` on your `CloudKitSynchronizer`, if you're not already doing it. (see https://mentrena.github.io/SyncKit/configuration#model-compatibility)

**Comment by sskjames** [comment]
Hi @mentrena, thank you for the suggestions.
I'd go with your suggestion of adding a new field with the right type, even though my app is still under development.
Thanks for reminding about the compatibilityVersion. I'll set that as well.
