### ISSUE TITLE
objects disappear on Device B if app is deleted on Device A

### ISSUE THREAD

**Issue by spotlessicode** [mentrena/SyncKit#18]
- Device A has objects: Obj1, Obj2
- Device B has objects: Obj3, Obj4
- sync downloads Obj1, Ob2, on Device B and sync downloads Obj3, Obj4 on Device A
- user deletes App on Device A
- at next sync on Device B Obj1 and Obj2 disappear, but they should stay, shouldn't?

**Comment by mentrena** [comment]
I can't reproduce this. Also, I can't imagine a case where SyncKit would automatically delete stuff unless you're telling it to...
For SyncKit to delete records from iCloud, they would have had to be deleted from a NSManagedObjectContext while it was being tracked by SyncKit, and then SyncKit would have to synchronise. All of that sounds very unlikely to happen as a result of the user simply deleting the app.
I would suggest debugging `-[QSCoreDataChangeManager targetContextDidSave:]` and `-[QSCoreDataChangeManager recordIDsMarkedForDeletionWithLimit:]` to see if records are indeed being deleted by SyncKit, and if so, I would investigate who is deleting the objects from Core Data and then using SyncKit to synchronise.
If that doesn't help, try to reproduce the issue using the example project and, if it doesn't happen there, check the differences between the CoreData setup in your project and the example project to see if you can spot the issue.

Feel free to reopen if you're positive the problem is caused by a bug in the library.
