### ISSUE TITLE
Is the synchronization real time?

### ISSUE THREAD

**Issue by i-schuetz** [mentrena/SyncKit#32]
Not sure if it makes sense to compare this with e.g. Realm Mobile Platform or Firebase for real time sync.

**Comment by mentrena** [comment]
Hi, not completely sure what you mean by real time here; You need to tell the library to synchronize, but you could just do that on `QSChangeManagerHasChangesNotification` to make it sync as soon as there are any changes. And you can use SyncKit to create a `CKSubscription` so your app delegate will get notified by CloudKit when there are new changes.
Regarding Realm Mobile Platform or Firebase, I'm not entirely familiar with those and this library is not intended as a replacement for some other technology. I imagine the functionality is similar, although of course SyncKit uses only CloudKit and iCloud.

**Comment by i-schuetz** [comment]
Okay. Sorry for the broad question. I assume that it wouldn't be possible, e.g. when using this with realm, to receive fain grained notifications - e.g. which objects or record changed. As this is internal of realm. Only that there was a general change in the database and reload.

**Comment by mentrena** [comment]
It's actually more like SyncKit works with Realm *because* Realm supports fine-grained notifications.

No reason you couldn't get notified for changes downloaded from iCloud. In fact, you could take a look at the SyncKitRealmExample example project where the notification is used to update the table view, I think that should answer your question.

**Comment by i-schuetz** [comment]
Oh right, this makes sense - the notifications are sent by the local database - I was thinking that they require the realm object server to work but this is wrong!

So this means that SyncKit can be used as a replacement for the Realm Object Server to some degree - at least for single user real time syncing. Any ideas about multiple users - e.g. a shared login (this is rather an iCloud question but embedding it here)?

**Comment by mentrena** [comment]
Maintaining multiple users would require more work on your side, but it would be possible.

First, you would need to detect when the iCloud user changes (`NSUbiquityIdentityDidChangeNotification`)
At that point, you would call `eraseLocal` on your current synchronizer, throw away your realm, and create a new realm for the new user plus a new synchronizer for the new realm.
Then synchronize to download all the existing data on iCloud for this user.

Depending on your use case this might be enough, but if you wanted to do something like keep the data for multiple users stored in disk (using different realms) and be able to seamlessly switch users without having to download all data again from iCloud, then that might require some changes in SyncKit, since at the moment it doesn't store the server token for incremental downloads per iCloud user, but just per iCloud container.

To be fair I imagine the case where two users keep changing the iCloud account on the same device is probably very infrequent...

**Comment by i-schuetz** [comment]
That was not what I meant! Should have made the question clearer. I mean e.g. to share a todo list. User A marks item as "done" in their device, user B sees this immediately in their device. With Realm Object Server you have 2 options - either you make user A and B authenticate with the same data, or something else more complicated with actual multiple user sharing of items. I was asking about the first simpler option - allowing users to share a realm by authenticating with the same data.

**Comment by mentrena** [comment]
I see, so you're talking about sharing data across different users on CloudKit.
CloudKit itself provides a public database, and also lets users shared private data selectively with other users, but SyncKit doesn't support those.
I would like to add some support for the latter (shared database) but still need to research what can and cannot be done.

**Comment by mentrena** [comment]
> allowing users to share a realm across multiple devices by authenticating with the same data 

If they're using the same iCloud account on their devices they would indeed see the same data when using SyncKit.

**Comment by i-schuetz** [comment]
> If they're using the same iCloud account on their devices they would indeed see the same data when using SyncKit.

Yeah, the problem is that you can't just create a new iCloud account to be shared (for something specific), like you could with another platforms. 

There's something in iOS 11 about sharing storage with family members but not sure how it works.

In any case please see this as a feature request - it would be great if sharing is possible! This is a decisive point for me and probably many others.

**Comment by mentrena** [comment]
No need for a new issue, it's already in my mind. Just need time and energy, it's not a simple feature ;)

**Comment by i-schuetz** [comment]
I see. Maybe you can start a gofundme or similar, I can image that it would get some traction considering that realm and firebase charge for this kind of functionality.

In any case, thanks for creating SyncKit and your answers!

**Comment by mentrena** [comment]
Cheers, closing here.
