### ISSUE TITLE
Crash on first synchronize: PendingRelationship

### ISSUE THREAD

**Issue by joelkraut** [mentrena/SyncKit#34]
As soon as I run I'm seeing a crash in `realmObjectClass()`, line 212. As far as I can tell it's because SyncKit added `PendingRelationship` to the schema, but because that's not a class in my namespace, `NSClassFromString` fails in both invocations. I'm not sure what the code is trying to do here, but I think you either need to not force-unwrap here, check against your module's namespace, or not add stuff to the same Realm I'm using. I think I remember seeing something about two different realms in the header for `QSRealmChangeManager`, but I don't see anything using it in the SyncKitRealm sample project.

Partial backtrace:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = breakpoint 9.1
  * frame #0: 0x000000010687c32d SyncKitRealmSwift`specialized RealmSwiftChangeManager.realmObjectClass(name:) at RealmSwiftChangeManager.swift:208 [opt]
    frame #1: 0x000000010687107c SyncKitRealmSwift`RealmSwiftChangeManager.setup() [inlined] SyncKitRealmSwift.RealmSwiftChangeManager.realmObjectClass(name: Swift.String) -> RealmSwift.Object.Type at RealmSwiftChangeManager.swift:0 [opt]
    frame #2: 0x000000010687106e SyncKitRealmSwift`RealmSwiftChangeManager.setup(self=0x00007f94d20089f0) at RealmSwiftChangeManager.swift:123 [opt]
    frame #3: 0x000000010687003d SyncKitRealmSwift`RealmSwiftChangeManager.init(persistenceRealmConfiguration=RealmSwift.Realm.Configuration @ 0x00007f8a75c853a0, targetRealmConfiguration=<unavailable>, recordZoneID=<unavailable>) at RealmSwiftChangeManager.swift:95 [opt]
    frame #4: 0x000000010688b0f0 SyncKitRealmSwift`static QSCloudKitSynchronizer.cloudKitSynchronizer(containerName:configuration:suiteName:) [inlined] SyncKitRealmSwift.RealmSwiftChangeManager.__allocating_init(persistenceRealmConfiguration: RealmSwift.Realm.Configuration, targetRealmConfiguration: RealmSwift.Realm.Configuration, recordZoneID: __ObjC.CKRecordZoneID) -> SyncKitRealmSwift.RealmSwiftChangeManager at QSCloudKitSynchronizer+RealmSwift.swift:0 [opt]
```

**Comment by mentrena** [comment]
Hi, the problem is that Realm will, by default, include every single Object subclass in your schema when you use the default configuration.
SyncKit uses Realm itself to keep track of changes in your model, and I haven't found a way to exclude those Realm classes from a default schema. If you know of a way to do that let me know :)

In the meantime, you can explicitly state what classes your schema should contain, like this:

```swift
var configuration = Realm.Configuration()
configuration.schemaVersion = 1

configuration.objectTypes = [QSCompany.self, QSEmployee.self]

realm = try! Realm(configuration: configuration)
```

This is from the SyncKitRealmSwiftExample project, you can take a look at how it's set up.
Hope that answers the question, feel free to reopen if I missed anything.
