### ISSUE TITLE
Performance of storing object notification for every object in Realm?

### ISSUE THREAD

**Issue by blwinters** [mentrena/SyncKit#35]
This is a fantastic library and will certainly go a long way toward helping me implement sync. I understand why Realm's collection notifications are not detailed enough to support the `QSRealmChangeManager`. However, it seems a little inelegant to register an object notification for every object managed by the Realm and keep them all in `NSMutableDictionary *objectNotificationTokens`. This looks like the best option, but I'm wondering, have you seen any performance issues with this?

**Comment by mentrena** [comment]
That's a very good point. Change tracking in Realm is quite painful compared to Core Data because of this requirement to explicitly observe objects and collections...
I haven't tested with huge data models so unfortunately I can't really answer that question. My assumption is that it wouldn't be a problem for most apps, but it's worth investigating.

**Comment by blwinters** [comment]
Thanks for the feedback. I'll run some isolated tests to measure memory expansion as tokens are added to a dictionary and report back.

**Comment by blwinters** [comment]
I created a simple app to test the increase in memory when adding notifications for every object. Here's the link: https://github.com/blwinters/ObjectNotifications.

It generates lists of items with a few basic properties. Running it in the simulator I came up with these results:

- 10 lists of 100 (1,000 objects): memory increased from 45.4 to 47.4 MB, 0.10 seconds. Net increase: 2 MB.
- 100 lists of 100 (10,000 objects): memory increased from 53.8 to 67.4 MB, 0.81 seconds. Net increase: 13.6 MB.
- 500 lists of 100 (50,000 objects): memory increased from 73.5 to 152 MB, 3.51 seconds. Net increase: 78.5 MB.
- 1,000 lists of 100 (100,000 objects): memory increased from 89.5 to 247 MB, 6.85 seconds. Net increase: 157.5 MB.
- 1,000 lists of 1,000 (1,000,000 objects): memory increased from 327 to 1750 MB, 58.74 seconds. Net increase: 1.4 GB.

These numbers may fluctuate a bit, of course, but it gives me enough information to know whether this approach will be okay for my project. I expect that engaged users will be adding ~50 objects a day, which I'm not confident will hold up well after a couple years of use. 

Perhaps more concerning is that Realm has built their own sync solution which is not included in the standard database, so I don't expect them to prioritize supporting this use case and it may fall down even if the memory isn't an issue.

For smaller databases this approach may work well, but I need to be a bit more conservative and will very likely be migrating to Core Data before launch.

**Comment by mentrena** [comment]
I ran your sample app and got similar results, it certainly doesn't scale for very big models...
So far I don't see a better way to do tracking though, I need per-object notifications to detect deletions and fine-grained modifications. 
One alternative I can think of, unless Realm improve their notifications, is having a change manager that you communicate changes directly to. It wouldn't be seamless to integrate in an app, but it would be easy to implement.
Or perhaps using introspection and KVO instead of Realm notifications would be an option. I imagine there would still be some overhead, but it would probably be significantly smaller (and linear)
Not a trivial problem in any case :/

Core Data sounds seems a safer bet at least for now.

**Comment by blwinters** [comment]
Yep, I agree with all of that. The change manager makes sense particularly if you have a relatively simple schema, but a large number of objects.

**Comment by aehlke** [comment]
Have we learned more about Realm scalability since these posts?

**Comment by aehlke** [comment]
IceCream manages to sync Realm to CloudKit with only one notificationToken per model, rather than object: https://github.com/caiyue1993/IceCream/blob/0b6b24a4eddc331361f3123eab48ef116b123161/IceCream/Classes/SyncObject.swift#L146

**Comment by aehlke** [comment]
I gave up on this and am in the middle of forking SyncKit + IceCream into a scalability-focused design with some tradeoffs https://github.com/lake-of-fire/BigSyncKit

**Comment by mentrena** [comment]
That's cool, I'm afraid at the moment I don't have the time to do anything other than basic maintenance.
I see you're using soft-deletes too, that's a move in the right direction given the limitations in Realm. Hope to be able to take inspiration from your changes when I do get time to come back :)

**Comment by aehlke** [comment]
Thanks for taking a look. I'll continue it independent from this project for now, please (obviously as open src) feel free to take anything back as you like. I'll be expanding it with postgres sync via supabase and other things that drift it further from this project's goals, so I think they can continue to serve different use cases.
