### ISSUE TITLE
Error after pod install

### ISSUE THREAD

**Issue by KingOlami** [mentrena/SyncKit#57]
Errors after installing via pod pod 'SyncKit/RealmSwift',  '~> 0.6.4'

`'Participant' is not a member type of 'CKShare'`
`CKRecordZone.ID` gives`'ID' is not a member type of 'CKRecord'` etc i got over 30 errors. Any reason for this happening?

**Comment by mentrena** [comment]
> Any reason for this happening?

Yes, if you look at the podspec you can see that SyncKit uses Swift 4.2. 
You must still be using Xcode 9 and that's why your compiler doesn't understand the code.
Ideally you should use the latest Xcode, but if you really need to use Xcode 9 then you could try with an older version of SyncKit (0.6.3)
