### ISSUE TITLE
Sharing more complex data models.

### ISSUE THREAD

**Issue by BlixLT** [mentrena/SyncKit#65]
As I understand, SyncKit supports only such "trees" where child objects have a to-one (many to one, or one to one) relationship to a parent object (parent <- child <- subchild). I need an ability to sync a more complex model. Lets say there is an entity called Property, that has one-to-many relationship to Child objects:
parent <- child1 (-> propertyA) <- subchild1 , .. , parent <- child2 (-> propertyA) <- subchild2. Have you ever thought about supporting sharing such models? If you have thought, but don't have plans to implement it, maybe you have any suggestions/recommendations how it could be achieved?

As far as I can see now in the Cloudkit dashboard - objects child1 and child2 have correct ckrecordids set for their to-one relationship to the entity Property in the shared database. The problem is that this Property object is not being shared. If it was, then I suppose all info could be seen/fetched on the device where a share was accepted. Maybe just including Property objects to the same ckshare object as parent could be enough. Or maybe creating a new ckshare that would include all Property objects as childs of that ckshare object could do the trick (when both ckshare objects are accepted). I hope you understood what I want to do and any suggestions are welcomed.

**Comment by mentrena** [comment]
It is not something I could do, based on how CloudKit works.

Taking your example:

parent <- child1 (-> propertyA) <- subchild1 , .. , parent <- child2 (-> propertyA) <- subchild2

You can definitely synchronise a model like this using the user's private database, there would be a single instance of `propertyA` and it would be properly connected to both `child1` and `child2` because they would be referencing it through their to-one relationship.
If your Core Data specifies inverse relationships, the to-many property on `propertyA` would also be correct and include both `child1` and `child2`.

When it comes to sharing though, the only way CloudKit lets you form a hierarchy of records is by using the `parent: CKReference?` property on `CKRecord`, and the parent can only be a single record. In your example it's clear that the parent of `child1` is `parent`, so you cannot specify `propertyA`. And it wouldn't make sense to make `child1` the "parent" of `propertyA`, since `propertyA` is also connected to `child2`. So, if sharing is important to you, you will need to restructure your model in a way that works for you, if that's possible.
Maybe you can have multiple instances of `propertyA`, instead of sharing a single one, maybe you can add extra logic in your app to add the missing connections after data has been synced...
The solution will depend on your specific model.

This was also discussed in #51, in case it helps.
